version: '3.8'

# Development-only docker-compose file
# Run with: docker-compose -f docker-compose.dev.yml up

services:
  postgres:
    image: pgvector/pgvector:pg16
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-ragstudio}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ragstudio}
      POSTGRES_DB: ${POSTGRES_DB:-ragstudio}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-ragstudio}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
