version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg16
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-ragstudio}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ragstudio}
      POSTGRES_DB: ${POSTGRES_DB:-ragstudio}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-ragstudio}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./packages/backend
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER:-ragstudio}:${POSTGRES_PASSWORD:-ragstudio}@postgres:5432/${POSTGRES_DB:-ragstudio}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CORS_ORIGINS=["http://localhost:5173","http://localhost:3000","http://localhost"]
      - BACKEND_HOST=0.0.0.0
      - BACKEND_PORT=8000
    ports:
      - "8000:8000"
    volumes:
      - upload-data:/app/uploads
      - ./packages/backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "5173:80"
    environment:
      - VITE_API_URL=http://localhost:8000

volumes:
  postgres-data:
  upload-data:
