[tool.poetry]
name = "rag-studio-backend"
version = "0.1.0"
description = "RAG Studio backend - FastAPI server for RAG experimentation"
authors = ["Jeroen Breemhaar <your@email.com>"]
license = "MIT"
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.115.0"
uvicorn = {extras = ["standard"], version = "^0.32.0"}
sqlalchemy = "^2.0.35"
greenlet = "^3.1.1"
asyncpg = "^0.30.0"
psycopg2-binary = "^2.9.9"
alembic = "^1.13.3"
pydantic = "^2.9.2"
pydantic-settings = "^2.6.0"
python-multipart = "^0.0.12"
openai = "^1.54.3"
langchain = "^0.3.7"
langchain-text-splitters = "^0.3.2"
pypdf = "^5.1.0"
python-dotenv = "^1.0.1"
pgvector = "^0.3.5"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.3"
pytest-asyncio = "^0.24.0"
httpx = "^0.27.2"
black = "^24.10.0"
ruff = "^0.7.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 100
target-version = ['py311']

[tool.ruff]
line-length = 100
target-version = "py311"

[tool.pytest.ini_options]
asyncio_mode = "auto"
testpaths = ["tests"]
